name: Node.js CI

on:
  push:
    branches:
      - master
      - "!dependabot/**"

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: cache node_modules
        id: node_modules_cache_id
        uses: actions/cache@v2
        with:
          path: |
            node_modules
          key: ${{ matrix.os }}-node-v${{ matrix.node }}-deps-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}

      - name: install dependencies
        run: yarn --check-files --frozen-lockfile --non-interactive

      - name: lint
        run: yarn lint

      - name: run tests
        run: yarn test

      - name: check build success
        run: yarn build
